overlay = "."
crate_src_path = ".."
bin_name = "pve-xtermjs"
maintainer = "Proxmox Support Team <support@proxmox.com>"

[source]
section = "admin"
homepage = "https://www.proxmox.com"
vcs_git = "git://git.proxmox.com/git/pve-xtermjs.git"
vcs_browser = "https://git.proxmox.com/?p=pve-xtermjs.git;a=summary"

[packages.bin]
summary = "HTML/JS Shell client for Proxmox projects"
description = """This package provides an xterm.js client/proxy for Proxmox\
  projects'  Hosts, Proxmox VE containers or Proxmox VE VM's serial-terminals.\
  """
